Let's a student data in python

In [6]:
name = 'Saad'
age = 8
GPA = 3.78
play_volleyball = True
print(name, age, GPA, play_volleyball)

Saad 8 3.78 True


## Make a view, change the original array, and display both arrays:

In [7]:
GPA = 3.89
print(GPA)

3.89


Lets try to get studnet in a more sophiscated mannger

In [8]:
print(f"the name of the student is {name} and is {age} years old")

the name of the student is Saad and is 8 years old


let's calculate Saad age in 15 years

In [9]:
age=age+15
print(name, age, GPA, play_volleyball)
print (f"the student name is {name} and will be {age} in 15 years Inshallah")

Saad 23 3.89 True
the student name is Saad and will be 23 in 15 years Inshallah


In [10]:
sports = ["cricket", "foot ball","table tenis", "base ball"]
sports[3]

'base ball'

In [11]:
sports.append('volleyball')
sports[4]
print("Saad is currently playing",sports)
sports[0:3]
print("Saad is currently playing",sports[0:3])

Saad is currently playing ['cricket', 'foot ball', 'table tenis', 'base ball', 'volleyball']
Saad is currently playing ['cricket', 'foot ball', 'table tenis']


## Calculating **Letter Grade**
- 2 or under D
- 3 or under C
- 3.8 or under B
- above 3.8 A


In [12]:
student_gpa =float(input("what is your GPA"))
if student_gpa <=2:
    letter_grade = "D"
elif student_gpa<=3:
    letter_grade = "C"
elif student_gpa<=3.8:
    letter_grade = "B"
else:
    letter_grade = "A"
print(f"studuent's Letter Grade is {letter_grade}")

studuent's Letter Grade is A


### Make a view, change the original array, and display both arrays:

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
x1 = arr1.view()
arr[0] = 42

print(arr1)
print(x1)

[42  2  3  4  5]
[42  2  3  4  5]


### Make a copy, change the original array, and display both arrays:

In [ ]:
import numpy as np

arr2 = np.array([1, 2, 3, 4, 5])
x2 = arr2.copy()
arr2[0] = 42

print(arr2)
print(x2)

[42  2  3  4  5]
[1 2 3 4 5]


### Make a view, change the view, and display both arrays:

In [ ]:
import numpy as np

arr3 = np.array([1, 2, 3, 4, 5])
x3 = arr3.view()
x3[0] = 31

print(arr3)
print(x3)

[31  2  3  4  5]
[31  2  3  4  5]


### Print the value of the base attribute to check if an array owns it's data or not:

In [29]:
import numpy as np
arr4 = np.array([1,2,3,4,5])
x4 = arr4.copy()
y4 = arr4.view()
print(x4.base)
print(y4.base)

None
[1 2 3 4 5]


###Print the shape of a 2-D array:

In [ ]:
import numpy as np
arr5 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr5.shape)

(2, 4)


(2, 4)

### Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [23]:
import numpy as np
arr10=np.array([1,2,3,4,5],ndmin=5)
print(arr10)
print('shape of an array :', arr10.shape)


[[[[[1 2 3 4 5]]]]]
shape of an array : (1, 1, 1, 1, 5)


#### Convert the following 1-D array with 12 elements into a 2-D array.

- The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
import numpy as np
arr6 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr8 = arr6.reshape(4,3)
print(newarr8)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D
### Example
- Convert the following 1-D array with 12 elements into a 3-D array.

- The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [ ]:
import numpy as np
arr7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr9 = arr7.reshape(2,3,2)
print(newarr9)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# RESHAPE EXAMPLE - Returns Copy or View?
### Check if the returned array is a copy or a view:

In [ ]:
import numpy as np
arr9 = np.array([1,2,3,4,5,6,7,8])
print(arr9.reshape(2,4).base)
# The example above returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


# Unknown Dimension
- You are allowed to have one "unknown" dimension.
- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
- Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
import numpy as np
arr8 = np.array([1,2,3,4,5,6,7,8])
newarr10 = arr8.reshape(2,2,-1)
print(newarr10)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening the arrays
- Flattening array means converting a multidimensional array into a 1D array.
- We can use reshape(-1) to do this.

In [32]:
import numpy as np
arr11 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr11)
newarr7 = arr11.reshape(-1)
print(newarr7)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


## Iterating Arrays
- Iterating means going through elements one by one.
- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
- If we iterate on a 1-D array it will go through each element one by one.

In [33]:
import numpy as np
arr12 = np.array([1,2,3,4])
for x5 in arr12:
    print(x5)

1
2
3
4


## Iterating 2-D Arrays
- In a 2-D array it will go through all the rows.

In [37]:
import numpy as np
arr13 = np.array([[1,2,3,4], [5,6,7,8]])
for x6 in arr13:
    print(x6)

[1 2 3 4]
[5 6 7 8]


#### Iterate on each scalar element of the 2-D array:

In [41]:
import numpy as np
arr14 = np.array([[1,2,3],[4,5,6]])
for x7 in arr14:
    for y7 in x7:
        print(y7)

1
2
3
4
5
6


## Iterating 3-D Arrays
- In a 3-D array it will go through all the 2-D arrays.
### Example
- Iterate on the elements of the following 3-D array:

In [42]:
import numpy as np
arr15 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x8 in arr15:
    print(x8)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### To return the actual values, the scalars, we have to iterate the arrays in each dimension.
### Example
- Iterate down to the scalars:

In [46]:
import numpy as np
arr16 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x9 in arr16:
    for y8 in x9:
        for z in y8:
         print(z)


1
2
3
4
5
6
7
8
9
10
11
12


### Example
- Iterate through the following 3-D array:

In [47]:
import numpy as np
arr17 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x10 in np.nditer(arr17):
    print(x10)

1
2
3
4
5
6
7
8


### Example
- Iterate through the array as a string:

In [48]:
import numpy as np
arr18 = np.array([1,2,3])
for x11 in np.nditer(arr18, flags=['buffered'], op_dtypes = ['S']):
    print(x11)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


### Example
- Iterate through every scalar element of the 2D array skipping 1 element:

In [49]:
import numpy as np
arr19 = np.array([[1,2,3,4],[5,6,7,8]])
for x12 in np.nditer(arr19[:,::2]):
    print(x12)

1
3
5
7


### Example
- Enumerate on following 1D arrays elements:

In [50]:
import numpy as np
arr20 = np.array([1,2,3])
for idx20, x13 in np.ndenumerate(arr20):
    print(idx20, x13)

(0,) 1
(1,) 2
(2,) 3


### Example
- Enumerate on following 2D array's elements:

In [51]:
import numpy as np
arr21 = np.array([[1,2,3,4], [5,6,7,8]])
for idx2, x14 in np.ndenumerate(arr21):
    print(idx2, x14)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Splitting NumPy Arrays
- Splitting is reverse operation of Joining.
- Joining merges multiple arrays into one and Splitting breaks one array into multiple.
- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
#### Example
- Split the array in 3 parts:

In [56]:
import numpy as np
arr22 = np.array([1,2,3,4,5,6])
newarr6 = np.split(arr22, 3)
print(newarr6)

[array([1, 2]), array([3, 4]), array([5, 6])]
