### Trigonometric Functions
- NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [1]:
# Find sine value of PI/2:
import numpy as np
x=np.sin(np.pi/2)
print(x)

1.0


In [3]:
import numpy as np
arr= np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x=np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [ ]:
import numpy as np
arr1 = np.array([90,180,270,360])
arr2= np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.deg2rad(arr1)
y = np.rad2deg(arr2)
print(x)
print(y)

[ 90 180 270 360]
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]


### Finding Angles
- Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).
- NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [9]:
import numpy as np
x=np.arcsin(1.0)
print(x)

1.5707963267948966


- Example: - Find the angle for all of the sine values in the array

In [10]:
import numpy as np
arr3 = np.array([1, -1, 0.1])
x3= np.arcsin(arr3)
print(x3)

[ 1.57079633 -1.57079633  0.10016742]


In [ ]:
import numpy as np
b1 = 4
p1= 3
x4 = np.hypot(b1,p1)
print(x4)

5.0
