### add function using numpy

In [15]:
import numpy as np
arr1 = np.array([11,12,13,14,15])
arr2 = np.array([6,7,8,9,10])
newarradd = np.add(arr1, arr2)
newarrsub = np.subtract(arr1, arr2)
newarrmulti = np.multiply(arr1, arr2)
newarrdivide = np.divide(arr1, arr2)
newarrpower= np.power(arr1, arr2)
newarrmod = np.mod(arr1, arr2)
newarrdivmod = np.divmod(arr1,arr2)
print(newarradd)
print(newarrsub)
print(newarrmulti)
print(newarrdivide)
print(newarrpower)
print(newarrmod)
print(newarrdivmod)

[17 19 21 23 25]
[5 5 5 5 5]
[ 66  84 104 126 150]
[1.83333333 1.71428571 1.625      1.55555556 1.5       ]
[     1771561     35831808    815730721  20661046784 576650390625]
[5 5 5 5 5]
(array([1, 1, 1, 1, 1]), array([5, 5, 5, 5, 5]))


### ufunction Rounding Decimals.

In [25]:
import numpy as np
arr3 = np.trunc([-3.2343, 4.34454])
arr4 = np.fix([-3.2343, 4.34454])
arr5 = np.around([-3.2343,3.6556], 2)
arr6 = np.floor([-3.2343,3.6556])
arr7 = np.ceil([-3.2343,3.6556])
print('truncate',arr3)
print('fix funtion',arr4)
print('around function',arr5)
print('floor function',arr6)
print('ceil function',arr7)

truncate [-3.  4.]
fix funtion [-3.  4.]
around function [-3.23  3.66]
floor function [-4.  3.]
ceil function [-3.  4.]


### Ufunction log numpy

- ExampleGet your own Python Server
- Find log at base 2 of all elements of following array:

In [33]:
import numpy as np
arr8 = np.arange(1,10)
print('base 2 log function array')
print(np.log2(arr8))
print('base 10 log function array')
print(np.log10(arr8))
print('natural log or base e function')
print(np.log(arr8))



base 2 log function array
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
base 10 log function array
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
natural log or base e function
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### Log at Any Base
- NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [43]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052
